### ISSUE TITLE
Padding in BCOP class seems to be ignored

### ISSUE THREAD

**Issue by lukas-schott** [ColinQiyangLi/LConvNet#4]
Paddings in the conv_module didn't work for me. I think this is due to the padding kwarg in the BCOP class init in lconvnet/layers/bcop.py / which is unused. 

https://github.com/ColinQiyangLi/LConvNet/blob/1d75bc55b39d4fd88fb6723ac81d5c9611ef4234/lconvnet/layers/bcop.py#L166

**Comment by ColinQiyangLi** [comment]
Thanks for your interest in this work and raising this issue! 

So far, all our analyses around orthogonal convolutions assume the padding to be exactly k // 2 on both sides (k is the kernel size). I just made a PR to include an assertion to prevent the silent failing of this issue. [here](https://github.com/ColinQiyangLi/LConvNet/pull/6).

What is your use case? It might be possible to find some workarounds for it. 

In the case where only the spatial dimension needs to be larger, it is possible to achieve that using [PixelShuffle](https://github.com/pytorch/pytorch/blob/84a31fb4e7fb1b5dbe9e42f5e1e30be4a0440189/torch/nn/modules/pixelshuffle.py#L5) without hurting the orthogonality.
